import nextConfig from 'eslint-config-next';
import neostandard from 'neostandard';

const eslintConfig = [
  ...neostandard({
    semi:  true,
    noJsx: true,
  }),
  {
    rules: {
      '@stylistic/key-spacing': [
        'error',
        {
          align:       'value',
          beforeColon: false,
          afterColon:  true
        }
      ],
      '@stylistic/no-multi-spaces': [
        'error',
        {
          exceptions: {
            Property:            true,
            VariableDeclarator:  true,
            ImportDeclaration:   true,
            TSTypeAnnotation:    true,
            TSPropertySignature: true,
          },
          ignoreEOLComments: true,
        }
      ],
      'key-spacing': [
        'error',
        {
          multiLine: {
            beforeColon: false,
            afterColon:  true,
            align:       'value',
          },
        },
      ],
    },
  },
  ...nextConfig,
  {
    ignores: [
      'node_modules/**',
      '.next/**',
      'out/**',
      'build/**',
      'next-env.d.ts',
      // Generated by openapi-typescript (pnpm gen:types).
      'src/types/api.gen.ts',
    ],
  },
];

export default eslintConfig;
