import { configDefaults, defineConfig } from 'vitest/config';
import react from '@vitejs/plugin-react';
import path from 'path';

export default defineConfig({
  plugins: [react()],
  test:    {
    environment: 'jsdom',
    setupFiles:  ['./src/__tests__/setup.ts'],
    globals:     true,
    // e2e/ holds the Playwright smoke suite (pnpm test:e2e); vitest must not
    // pick up its *.spec.ts files.
    exclude:     [...configDefaults.exclude, 'e2e/**'],
    // The fast-check property tests render components ~100 times each. On
    // a CI runner that can exceed the 5 s default.
    testTimeout: process.env.CI ? 30_000 : 5_000,
    // pnpm test:coverage. The thresholds sit 1-2 points below the measured
    // coverage so a change that drops it fails CI; raise them as coverage
    // grows, never lower them to make a change pass.
    coverage:    {
      provider: 'v8',
      include:  ['src/**/*.{ts,tsx}'],
      exclude:  [
        'src/**/__tests__/**',
        'src/**/*.test.{ts,tsx}',
        // Generated by openapi-typescript (pnpm gen:types): types only.
        'src/types/api.gen.ts',
        'src/**/*.d.ts',
      ],
      reporter:   ['text-summary', 'html'],
      thresholds: {
        // Measured 2026-10-05: lines 97.67, statements 96.67,
        // functions 96.59, branches 91.37.
        lines:      96,
        statements: 95,
        functions:  95,
        branches:   90,
      },
    },
  },
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
    },
  },
});
